name: Push

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-and-test:
    name: Build and Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Compile and run unit tests
        run: ./gradlew assembleDebug testDebugUnitTest --stacktrace
